1
artemihx/backend_pozd pull request #1
Opened 2023-10-15 09:28 UTC by artemihx

2023-10-15 09:39 UTC, RetmixX requested changes
Нету разделения  на прод и дев. Переделать и еще раз на проверку.

2023-10-15 09:39 UTC, RetmixX commented on .env
Без данных, пользователь сам уже их тут пропишет

2023-10-15 09:39 UTC, RetmixX commented on docker-compose.yml
> +      - "80:80"
Порты вынести в .env

2023-10-15 09:39 UTC, RetmixX commented on docker-compose.yml
> +      - 5432:5432
Так же порт надо вынести в .env

2023-10-15 09:39 UTC, RetmixX commented on docker-compose.yml
> +      - POSTGRES_DB=${DB_NAME}
У переменных окружениях стоит использовать значения по умолчанию. ${DB_NAME:-retmix}

2023-10-15 09:39 UTC, RetmixX commented on docker-compose.yml
> +      - 8080:8080
Так же нужно вынести порт

2023-10-15 09:39 UTC, RetmixX commented on docker-compose.yml
> +    volumes:
Тут стоит еще использовать volume для бд.
volumes:
    db_data:
        driver: local
        
Как пример

2023-10-15 09:48 UTC, artemihx commented on .env
.env не должен быть заполнен данными бд? просто DB_NAME и остальное пустым оставлять?

2023-10-15 16:21 UTC, jurapro commented on .env
Сделай .env.example с тестовыми данными (не реальными). Это общепринятая практика, пользователи клонируют твою репу, копируют файл, меняют на свое

2023-10-16 02:50 UTC, RetmixX requested changes
Поправить замечания

2023-10-16 02:50 UTC, RetmixX commented on dev/php/Dockerfile
> +        && docker-php-ext-install -j$(nproc) iconv mbstring mysqli pdo_mysql zip \
либы для mysql не потребуются. Вместо них нужно поставить либы для постгреса

2023-10-16 02:50 UTC, RetmixX commented on prod/.env
убрать из гитхаба

2023-10-16 02:50 UTC, RetmixX commented on prod/docker-compose.yml
> +    volumes:
В проде лучше не прокидывать волюмы

2023-10-16 02:50 UTC, RetmixX commented on prod/docker-compose.yml
> +    volumes:
Лучше не прокидывать волюмы в проде

2023-10-16 02:50 UTC, RetmixX commented on prod/docker-compose.yml
> +    volumes:
Это можно оставить

2023-10-16 02:50 UTC, RetmixX commented on prod/nginx/nginx.conf
> +    server_name hello.dev;
Вынеси server_name в переменную окружения

2023-10-16 02:50 UTC, RetmixX commented on prod/php/Dockerfile
> +        && docker-php-ext-install -j$(nproc) iconv mbstring mysqli pdo_mysql zip \
Так же замени на постгрес

2023-10-16 10:47 UTC, Skiexx requested changes
Неплохо, но нужно подредактировать еще)

2023-10-16 10:47 UTC, Skiexx commented on dev/docker-compose.yml
> +      - ./db_data:/var/lib/postgresql/data
```suggestion
      - db_data:/var/lib/postgresql/data
```
Убери ./ иначе она отсылается на локальную папку а не на volume созданный докером

2023-10-16 10:47 UTC, Skiexx commented on dev/docker-compose.yml
> +      - ./postgres:/docker-entrypoint-initdb.d/
```suggestion
```
Энтрипоинт редко меняют, но можешь оставить.

2023-10-16 10:47 UTC, Skiexx commented on dev/php/Dockerfile
> +FROM php:8.1-fpm-alpine
```suggestion
FROM php:8.2-fpm-alpine
```
Используем актуальные версии

2023-10-16 10:47 UTC, Skiexx commented on prod/docker-compose.yml
> +      - ./db_data:/var/lib/postgresql/data
```suggestion
      - db_data:/var/lib/postgresql/data
```
Аналогично с комментарием выше

2023-10-16 10:47 UTC, Skiexx commented on prod/nginx/nginx.conf
> +    server_name hello.dev;
https://hub.docker.com/_/nginx
Почитай в hub про использование переменных в nginx
Using environment variables in nginx configuration (new in 1.19)

2023-10-16 10:47 UTC, Skiexx commented on prod/php/Dockerfile
> +FROM php:8.1-fpm-alpine
```suggestion
FROM php:8.2-fpm-alpine
```
Аналогично

2023-10-16 10:47 UTC, Skiexx commented on prod/docker-compose.yml
> +  adminer:
Админер в prod не нужен

2023-10-16 10:51 UTC, artemihx commented on dev/php/Dockerfile
> +FROM php:8.1-fpm-alpine
а в тз 8.1 же

2023-10-16 11:56 UTC, Skiexx approved these changes
ฅ•ω•ฅ
С кофейком пойдет

2023-10-16 12:59 UTC, RetmixX requested changes
Проект с дампом бд(от тут пока вообще не нужен), надо вынести за пределы прод и дев сборки ибо это двойная работа. В прод сборке у тебя контейнеры без приложения вообще

2023-10-16 12:59 UTC, RetmixX commented on dev/nginx/nginx.conf
Добавь сюда админер

2023-10-16 12:59 UTC, RetmixX commented on dev/docker-compose.yml
> +      SERVER_NAME: "hello.dev"
localhost

2023-10-16 13:01 UTC, jurapro approved these changes
Похоже на то, что можно использовать дальше)

2023-10-17 02:25 UTC, RetmixX approved these changes
Отлично

2023-10-17 02:36 UTC, merged